### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/mybook-diary#1]
1. 책장
- [x] 책장 추가 기능

- [x] 책장 리스트 listview.builder로 만들기

- [ ] 책장 열기 기능(책장 객체 주고, 화면 전환)

- [ ] 상태줄에 책장 편집/삭제 기능

2. 책
- [ ] 책 추가 기능 

- [x] 추가된 책들 gridview로 보여주기

- [ ] 책 상세 보기 화면 전환

- [ ] 책 삭제/수정 기능 만들기

3. 책 분류

- [ ] 책장 모아보기

- [ ] 모든 책/ 읽고 있는 책/ 다 읽은 책/ 나중에 읽을 책 분류 select box 만들기

- [ ] select 했을때 조건에 맞는 책들 불러오는 기능

2. 책

- [ ] 다 읽은책 표시

- [ ] 읽고 있는책: 몇%읽었는지 표시

4. learning plan 만들기/weekly 진행도

**Comment by kangsudal** [comment]
10/29~ 30 15:52
SHA c39cc59
책장 리스트 listview.builder로 만들기 완료

~31 2:17
SHA 7eef345
책장 추가 기능 완료

**Comment by kangsudal** [comment]
추가된 책들 gridview로 보여주기
레이아웃 완료
~11/6 4:56

Drawer 메뉴 클릭시 해당페이지로 화면전환 (2일)
1aabc3b 2be1a34 eec8aec df7858d

floating 버튼 클릭시 책 추가 레이아웃 (3일)
194739f 1ae67fa 32fe3f9 d10ec70 fef6d1a

**Comment by kangsudal** [comment]
책 추가 기능
책 상세 보기 화면 전환
책 삭제/수정 기능 만들기
책장 열기 기능(책장 객체 주고, 화면 전환)

하는중
05cc585  daf4a37  d0f2bb3  610b7d3  57092d0  a2e0c40

~ 11/14

**Comment by kangsudal** [comment]
Provider
Firebase

Provider로 코드를 좀 깔끔하게 만들고싶다. 데이터를 꺼내오고 입력하는 출구를 통일하고싶다. 데이터: 책, 책장, 사용자 정보

Firebase: 데이터 영속성. 어플 껐다켜도 리셋안되게 저장하는 방법 찾아봤는데 device local storage를 사용하는 sqlite 이용 방법도 있지만, 나는 구글 서비스 이용방식을 써보고싶어서 firebase라는것에 자꾸 관심을 갖게 되는것같다. 영어로된자료들을 읽고보는데 쉽게 피곤하고 지쳐서 속도가 더디지만, 꼭 사용하는 방법을 알고싶다.

Flutter와 Firebase를 익숙하게 다루는 다른 사람들이 어떻게 쓰는지 구경을 많이 하는게 먼저같다.

그다음에 firebase 사용하는 코드에서 받아온 instance를 provider에 저장시켜서 꺼냈다 넣었다 하는법에 초점을 맞추는 순서가 지금의 나에게 옳은것 같다~

**Comment by kangsudal** [comment]
> 
> 
> Provider
> Firebase
> 
> Provider로 코드를 좀 깔끔하게 만들고싶다. 데이터를 꺼내오고 입력하는 출구를 통일하고싶다. 데이터: 책, 책장, 사용자 정보
> 
> Firebase: 데이터 영속성. 어플 껐다켜도 리셋안되게 저장하는 방법 찾아봤는데 device local storage를 사용하는 sqlite 이용 방법도 있지만, 나는 구글 서비스 이용방식을 써보고싶어서 firebase라는것에 자꾸 관심을 갖게 되는것같다. 영어로된자료들을 읽고보는데 쉽게 피곤하고 지쳐서 속도가 더디지만, 꼭 사용하는 방법을 알고싶다.
> 
> Flutter와 Firebase를 익숙하게 다루는 다른 사람들이 어떻게 쓰는지 구경을 많이 하는게 먼저같다.
> 
> 그다음에 firebase 사용하는 코드에서 받아온 instance를 provider에 저장시켜서 꺼냈다 넣었다 하는법에 초점을 맞추는 순서가 지금의 나에게 옳은것 같다~

https://www.youtube.com/watch?v=j_SJ7XmT2MM

이런 강좌를 찾게됐는데 지금의 내게 아주 적절한것같다 
아직은 안따라하고 스트레스 안받고 익숙해지게, 큰 흐름 보고싶어서 쭉 보고있는 중이다.

![firebase와 provider](https://user-images.githubusercontent.com/32862869/69622578-8d441c00-1084-11ea-977e-cbd6805f8d2d.PNG)
![firebase와 provider2](https://user-images.githubusercontent.com/32862869/69622895-30953100-1085-11ea-93c1-8c570358e026.PNG)
![firebase와 provider3](https://user-images.githubusercontent.com/32862869/69623045-7fdb6180-1085-11ea-966a-adb35780c316.PNG)

**Comment by kangsudal** [comment]
Flutter & Firebase App Tutorial #17 - Firestore User Records
https://www.youtube.com/watch?v=EA7973HI93E

![Firestore User Records](https://user-images.githubusercontent.com/32862869/69685593-4b58bb80-1100-11ea-98c8-52e4203fb39d.PNG)
![Firestore User Records2](https://user-images.githubusercontent.com/32862869/69685594-4b58bb80-1100-11ea-84a6-d05d0c64ae5f.PNG)
![Firestore User Records3](https://user-images.githubusercontent.com/32862869/69685595-4b58bb80-1100-11ea-9aeb-6100afb4fffb.PNG)
![Firestore User Records4](https://user-images.githubusercontent.com/32862869/69685666-8f4bc080-1100-11ea-9125-6ac168f09ee3.PNG)
